name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Xcode
        uses: apple/setup-xcode@v3
        with:
          xcode-version: '16.0'

      - name: Build and Archive
        run: |
          xcodebuild -workspace SafariSearchEngine.xcodeproj -scheme SafariSearchEngine -configuration Release archive -archivePath $PWD/build/SafariSearchEngine.xcarchive

      - name: Export .app
        run: |
          xcodebuild -exportArchive -archivePath $PWD/build/SafariSearchEngine.xcarchive -exportPath $PWD/build -exportOptionsPlist $PWD/SafariSearchEngine.xcodeproj/ExportOptions.plist

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Release notes
          files: $PWD/build/SafariSearchEngine.app